services:
  db:
    image: mysql:latest
    container_name: shelved_db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: shelved_backend
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "${BACKEND_PORT}:${PLAIN_BACKEND_PORT}"
    volumes:
      - ./:/app
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json

volumes:
  mysql_data:
